name: Run 18:10

on:
  workflow_dispatch:
  schedule:
     - cron: '10 10 * * *'
     - cron: '25 10 * * *'
     - cron: '40 10 * * *'
     - cron: '00 11 * * *'
     - cron: '20 11 * * *'
     - cron: '40 11 * * *'
     - cron: '00 12 * * *'
     - cron: '20 12 * * *'
     - cron: '40 12 * * *'
     - cron: '00 13 * * *'
     - cron: '15 13 * * *'
     - cron: '30 13 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Timezone to Asia/Shanghai
        run: |
          date
          sudo timedatectl set-timezone Asia/Shanghai
          date

      - name: Unzip protected runner.zip with password from secret
        run: unzip -P "${{ secrets.RUNNER_ZIP_PASSWORD }}" runner.zip -d runner

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: nrt.vultrcr.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run
        run: |
          cd ./runner && mkdir -p logs && ./run.sh "$(pwd)/list_all.json" 0.2~0.5
