name: Run 6:30

on:
  workflow_dispatch:
  schedule:
    - cron: '30 22 * * *'
    - cron: '40 22 * * *'
    - cron: '50 22 * * *'
    - cron: '00 23 * * *'
    - cron: '10 23 * * *'
    - cron: '20 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Timezone to Asia/Shanghai
        run: |
          date
          sudo timedatectl set-timezone Asia/Shanghai
          date

      - name: Unzip protected runner.zip with password from secret
        run: unzip -P "${{ secrets.RUNNER_ZIP_PASSWORD }}" runner.zip -d runner

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: nrt.vultrcr.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run
        run: |
          cd ./runner && mkdir -p logs && ./run.sh "$(pwd)/list_6_30.json" 0.2~0.5
