name: Run 12:00

on:
  workflow_dispatch:
  schedule:
    - cron: '00 4 * * *'
    - cron: '30 4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Timezone to Asia/Shanghai
        run: |
          date
          sudo timedatectl set-timezone Asia/Shanghai
          date

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: nrt.vultrcr.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run
        run: |
          cd ./runner && mkdir -p logs && ./run.sh "$(pwd)/school_list_12_00.json" 0.2~0.5
